# Generated by Django 5.2.3 on 2025-07-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0004_groupjoinrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroommember",
            name="last_read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
