# Generated by Django 4.2.7 on 2025-06-29 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
        ('venues', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventvendor',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_bookings', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='eventtimeline',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventtimeline',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='eventnote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventnote',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventguest',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventdocument',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventchecklist',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventbudget',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventbudget',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.eventtype'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='venues.venue'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='venues.venuepackage'),
        ),
        migrations.AlterUniqueTogether(
            name='eventvendor',
            unique_together={('event', 'vendor', 'vendor_type')},
        ),
    ]
