# Generated by Django 5.2.3 on 2025-06-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="format",
            field=models.CharField(
                blank=True,
                help_text="Format (e.g., In-person, Online, Drive-through)",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="skill_level",
            field=models.CharField(
                blank=True,
                help_text="Skill level (e.g., Beginner, Intermediate, Advanced)",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="sub_category",
            field=models.CharField(
                blank=True,
                help_text="Sub-category (e.g., Football, Java, Baking)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="tags",
            field=models.JSONField(
                blank=True, default=list, help_text="Tags for advanced filtering"
            ),
        ),
    ]
